# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - fct-euw-legalcb-legalapi-test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'LegalApi'
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'frontend/package-lock.json'
      
      - name: Build Angular (test configuration)
        working-directory: frontend
        run: |
          npm ci
          npm run build:test || npx ng build --configuration test --base-href /app/
      
      - name: Copy Angular dist into Functions wwwroot/app
        shell: pwsh
        run: |
          if (Test-Path "LegalApi/wwwroot/app") { Remove-Item -Recurse -Force "LegalApi/wwwroot/app" }
          New-Item -ItemType Directory -Force -Path "LegalApi/wwwroot/app" | Out-Null
          $distRoot = Get-ChildItem -Path frontend/dist -Directory | Select-Object -First 1
          if (-not $distRoot) { throw "Angular dist folder not found under frontend/dist" }
          $browser = Join-Path $distRoot.FullName 'browser'
          $source = $distRoot.FullName
          if (Test-Path $browser) { $source = $browser }
          Copy-Item -Recurse -Force -Path "$source/*" -Destination "LegalApi/wwwroot/app"

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Publish Function App'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet publish --configuration Release --output ./publish_output
          popd

      - name: Copy Angular dist into publish output (app/)
        shell: pwsh
        run: |
          $distRoot = Get-ChildItem -Path frontend/dist -Directory | Select-Object -First 1
          if (-not $distRoot) { throw "Angular dist folder not found under frontend/dist" }
          $browser = Join-Path $distRoot.FullName 'browser'
          $source = $distRoot.FullName
          if (Test-Path $browser) { $source = $browser }
          New-Item -ItemType Directory -Force -Path "LegalApi/publish_output/app" | Out-Null
          Copy-Item -Recurse -Force -Path "$source/*" -Destination "LegalApi/publish_output/app"

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'fct-euw-legalcb-legalapi-test'
          slot-name: 'Production'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/publish_output'

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_58D946C235CD461AB7C23497269798C8 }}



